"""Wizard dialog for assembling, previewing, and generating audit reports."""

from typing import Any

from PySide6.QtCore import QThread, Signal
from finauditpro.ui.widgets.custom_combo import CustomComboBox
from finauditpro.ui.widgets.custom_combo import CustomComboBox
from PySide6.QtWidgets import (
    QComboBox,
    QDialog,
    QFormLayout,
    QGroupBox,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QMessageBox,
    QProgressBar,
    QPushButton,
    QTextEdit,
    QVBoxLayout,
    QWidget,
)

from finauditpro.application.report_dtos import GenerateReportDTO
from finauditpro.application.services.report_service import ReportService


class ReportWorkerThread(QThread):
    """Off-thread worker for report generation and rendering."""

    finished_signal = Signal(object)
    error_signal = Signal(str)

    def __init__(self, service: ReportService, dto: GenerateReportDTO) -> None:
        super().__init__()
        self.service = service
        self.dto = dto

    def run(self) -> None:
        try:
            res = self.service.generate_report(self.dto)
            self.finished_signal.emit(res)
        except Exception as ex:
            self.error_signal.emit(str(ex))


class ReportWizardDialog(QDialog):
    """Wizard for generating audit reports off-thread with live query previews."""

    def __init__(
        self,
        engagement_id: str,
        report_service: ReportService,
        parent: QWidget | None = None,
    ) -> None:
        super().__init__(parent)
        self.engagement_id = engagement_id
        self.report_service = report_service
        self.worker: ReportWorkerThread | None = None

        self.setWindowTitle("Audit Report Generation Wizard")
        self.resize(650, 520)

        self._init_ui()
        self._load_templates()

    def _init_ui(self) -> None:
        layout = QVBoxLayout(self)

        # 1. Non-Statutory Template Guidance Card
        guidance_box = QGroupBox("TEMPLATE GUIDANCE NOTICE")
        guidance_box.setStyleSheet("QGroupBox { font-weight: bold; color: #38bdf8; }")
        g_layout = QVBoxLayout(guidance_box)
        lbl_g = QLabel(
            "<b>NOTICE:</b> Statutorily-prescribed wording (e.g. SA 700 audit opinion, CARO clauses) "
            "must be provided as auditor-reviewed templates carrying <code>verified_statutory: False</code>.<br>"
            "This app assembles real query data; it does <b>NOT</b> author statutory legal opinions from memory."
        )
        lbl_g.setWordWrap(True)
        lbl_g.setStyleSheet("color: #e2e8f0; font-size: 11px;")
        g_layout.addWidget(lbl_g)
        layout.addWidget(guidance_box)

        # 2. Input Form
        form = QFormLayout()
        self.tpl_combo = CustomComboBox()
        self.tpl_combo.currentIndexChanged.connect(self._on_template_selected)

        self.title_input = QLineEdit("Audit Findings & Internal Control Exceptions Summary")
        self.author_input = QLineEdit("Lead Auditor")

        form.addRow("Report Template:", self.tpl_combo)
        form.addRow("Report Title:", self.title_input)
        form.addRow("Generated By (Auditor):", self.author_input)

        layout.addLayout(form)

        # 3. Assembled Content Preview Panel
        preview_box = QGroupBox("Real Query Assembled Content Preview")
        p_layout = QVBoxLayout(preview_box)
        self.preview_text = QTextEdit()
        self.preview_text.setReadOnly(True)
        p_layout.addWidget(self.preview_text)
        layout.addWidget(preview_box)

        # Progress Bar
        self.progress_bar = QProgressBar()
        self.progress_bar.setRange(0, 0)
        self.progress_bar.hide()
        layout.addWidget(self.progress_bar)

        # 4. Actions
        btn_box = QHBoxLayout()
        btn_preview = QPushButton("Refresh Data Preview")
        btn_preview.clicked.connect(self._update_preview)

        btn_generate = QPushButton("Generate Report (PDF)")
        btn_generate.setStyleSheet("background-color: #3b82f6; color: white; font-weight: bold;")
        btn_generate.clicked.connect(self._on_generate_clicked)

        btn_cancel = QPushButton("Cancel")
        btn_cancel.clicked.connect(self.reject)

        btn_box.addWidget(btn_preview)
        btn_box.addWidget(btn_generate)
        btn_box.addWidget(btn_cancel)
        layout.addLayout(btn_box)

    def _load_templates(self) -> None:
        self.tpl_combo.clear()
        templates = self.report_service.list_templates()

        for t in templates:
            self.tpl_combo.addItem(f"{t.name} (v{t.version})", t.id)

        self._update_preview()

    def _on_template_selected(self) -> None:
        self._update_preview()

    def _update_preview(self) -> None:
        data = self.report_service.assemble_report_data(self.engagement_id)
        preview_str = (
            f"=== REAL QUERY ASSEMBLED DATA SNAPSHOT ===\n"
            f"Data As-Of: {data['as_of']}\n"
            f"• Accepted Findings Count: {len(data['findings'])}\n"
            f"• Risk Register Items: {len(data['risks'])}\n"
            f"• Working Papers Count: {len(data['working_papers'])}\n\n"
            f"Sample Finding: {data['findings'][0]['title'] if data['findings'] else 'No findings recorded.'}"
        )
        self.preview_text.setText(preview_str)

    def _on_generate_clicked(self) -> None:
        tpl_id = self.tpl_combo.currentData()
        title = self.title_input.text().strip()
        author = self.author_input.text().strip()

        if not title:
            QMessageBox.warning(self, "Validation Error", "Please enter a report title.")
            return

        dto = GenerateReportDTO(
            engagement_id=self.engagement_id,
            template_id=tpl_id,
            title=title,
            generated_by=author,
        )

        self.progress_bar.show()
        self.worker = ReportWorkerThread(self.report_service, dto)
        self.worker.finished_signal.connect(self._on_generation_finished)
        self.worker.error_signal.connect(self._on_generation_error)
        self.worker.start()

    def _on_generation_finished(self, report: Any) -> None:
        self.progress_bar.hide()
        QMessageBox.information(
            self,
            "Report Generated",
            f"Report '{report.title}' generated successfully!\nStatus: {report.status.value} (DRAFT Watermarked)",
        )
        self.accept()

    def _on_generation_error(self, err_msg: str) -> None:
        self.progress_bar.hide()
        QMessageBox.critical(self, "Generation Error", f"Report generation failed: {err_msg}")
