"""Authoritative Standards on Auditing (SA 200 - SA 706) methodology catalog."""

from finauditpro.domain.audit_matrix_entities import AssertionEnum
from finauditpro.domain.methodology_entities import (
    MethodologyProcedureTemplate,
    MethodologyRiskTemplate,
    StandardCategoryEnum,
    StandardDefinition,
    StandardRequirement,
)


def _build_sa_standard(
    code: str, title: str, req_code: str, req_title: str, req_desc: str,
    rsk_code: str, rsk_title: str, area: str, rsk_level: str,
    rsk_assertions: list[AssertionEnum], proc_code: str, proc_title: str,
    proc_obj: str, proc_type: str, proc_assertions: list[AssertionEnum],
    pop_def: str, meth_guide: str, evidence: str, wp_ref: str, wp_title: str,
    wp_sections: list[tuple[int, str, str]], checklist: list[str],
) -> StandardDefinition:
    proc = MethodologyProcedureTemplate(
        procedure_code_prefix=proc_code, title=proc_title, objective=proc_obj,
        procedure_type=proc_type, assertions=proc_assertions, population_definition=pop_def,
        methodology_guidance=meth_guide, expected_evidence=evidence, working_paper_ref=wp_ref,
        working_paper_title=wp_title, wp_sections=wp_sections, review_checklist=checklist,
    )
    risk = MethodologyRiskTemplate(
        risk_code_prefix=rsk_code, risk_title=rsk_title, audit_area=area,
        inherent_risk_level=rsk_level, assertions=rsk_assertions, procedures=[proc],
    )
    req = StandardRequirement(
        requirement_code=req_code, title=req_title, description=req_desc,
        statutory_reference=f"{code} (ICAI AASB)", risks=[risk],
    )
    return StandardDefinition(
        standard_code=code, title=title, category=StandardCategoryEnum.STANDARD_ON_AUDITING,
        authoritative_source="ICAI Auditing and Assurance Standards Board", effective_date="2018-04-01",
        requirements=[req],
    )


def get_sa_standards_catalog() -> list[StandardDefinition]:
    """Return canonical catalog of ICAI Standards on Auditing."""
    return [
        _build_sa_standard(
            code="SA 200", title="Overall Objectives of the Independent Auditor",
            req_code="SA200-R1", req_title="Professional Skepticism & Audit Risk Reduction",
            req_desc="Plan and perform audit with professional skepticism recognizing circumstances may cause material misstatement.",
            rsk_code="RSK-SA200-SKEP", rsk_title="Audit Risk of Overlooking Contradictory Evidence", area="General Audit Planning",
            rsk_level="HIGH", rsk_assertions=[AssertionEnum.COMPLETENESS, AssertionEnum.ACCURACY],
            proc_code="PROC-SA200-EVAL", proc_title="Evaluation of Audit Evidence Objectivity",
            proc_obj="Ensure evidence obtained from client is corroborated by independent source data (SA 200.15).",
            proc_type="Risk Assessment & Planning", proc_assertions=[AssertionEnum.COMPLETENESS],
            pop_def="Entire audit engagement documentation and management responses.",
            meth_guide="Document inquiry corroboration and challenge management assumptions.",
            evidence="Engagement letter, independence declarations, audit strategy memorandum.",
            wp_ref="WP-SA200-OBJECTIVES", wp_title="Audit Strategy & Professional Skepticism Matrix",
            wp_sections=[(1, "1. Engagement Scope", "Verify objectives and preconditions."), (2, "2. Risk Assessment", "Document engagement risk level.")],
            checklist=["Are preconditions for audit confirmed?", "Has professional skepticism been maintained?"],
        ),
        _build_sa_standard(
            code="SA 230", title="Audit Documentation",
            req_code="SA230-R1", req_title="Sufficient & Appropriate Audit Documentation Assembly",
            req_desc="Prepare audit documentation on a timely basis to provide sufficient appropriate record of basis for auditor's report.",
            rsk_code="RSK-SA230-DOC", rsk_title="Inadequate Working Paper Trail / Unsubstantiated Findings", area="Audit Documentation",
            rsk_level="HIGH", rsk_assertions=[AssertionEnum.ACCURACY, AssertionEnum.COMPLETENESS],
            proc_code="PROC-SA230-REV", proc_title="Working Paper Completeness & Assembly Verification",
            proc_obj="Assemble final audit file within 60 days of report date without deleting superseded work (SA 230.14).",
            proc_type="Quality Control & Review", proc_assertions=[AssertionEnum.COMPLETENESS],
            pop_def="All generated working papers and evidence files.",
            meth_guide="100% verification of working paper signoffs and evidence cross-referencing.",
            evidence="Signed working papers, reviewer signoff logs, file assembly manifest.",
            wp_ref="WP-SA230-FILE-ASSEMBLY", wp_title="Audit File Assembly & Documentation Checklist",
            wp_sections=[(1, "1. File Inventory", "List of all working papers and signoff statuses."), (2, "2. Timely Assembly", "Verify assembly within 60-day limit.")],
            checklist=["Are all WP steps signed off by preparer and reviewer?", "Is evidence referenced bidirectionally?"],
        ),
        _build_sa_standard(
            code="SA 240", title="The Auditor's Responsibilities Relating to Fraud",  # ignore
            req_code="SA240-R1", req_title="Management Override of Controls & Non-Standard Journal Entries",
            req_desc="Design and perform procedures to test journal entries and evaluate accounting estimates for management bias.",
            rsk_code="RSK-SA240-OVERRIDE", rsk_title="Management Override of Internal Financial Controls", area="Journal Entries & Estimates",
            rsk_level="HIGH", rsk_assertions=[AssertionEnum.OCCURRENCE, AssertionEnum.ACCURACY, AssertionEnum.CUT_OFF],
            proc_code="PROC-SA240-JRN", proc_title="Forensic Testing of Journal Entries & Unusual Adjustments",
            proc_obj="Identify and test high-risk, round-number, weekend, and post-closing manual journal entries (SA 240.32).",
            proc_type="Substantive Management Override Procedure", proc_assertions=[AssertionEnum.OCCURRENCE, AssertionEnum.ACCURACY],
            pop_def="All GL manual journal vouchers posted throughout the financial year and post-close period.",
            meth_guide="Stratify entries with Benford's Law and targeted query filters (weekend, round numbers, privileged users).",
            evidence="Journal vouchers, approval slips, underlying tax invoices, bank debit records.",
            wp_ref="WP-SA240-JOURNAL-OVERRIDE", wp_title="SA 240 Journal Entry & Management Override Audit Schedule",
            wp_sections=[(1, "1. Extraction Criteria", "Log of query parameters for high-risk JVs."), (2, "2. Sample Testing", "Detailed voucher vouching and approvals.")],
            checklist=["Were non-standard post-closing JVs tested?", "Was management bias in estimates evaluated?"],
        ),
        _build_sa_standard(
            code="SA 250", title="Consideration of Laws and Regulations in an Audit",
            req_code="SA250-R1", req_title="Identification of Non-Compliance with Direct & Fundamental Laws",
            req_desc="Obtain general understanding of legal and regulatory framework applicable to the entity and compliance status.",
            rsk_code="RSK-SA250-NOCLAR", rsk_title="Unrecorded Fines, Penalties & Disqualifications (NOCLAR)", area="Statutory & Regulatory",
            rsk_level="HIGH", rsk_assertions=[AssertionEnum.COMPLETENESS, AssertionEnum.RIGHTS_AND_OBLIGATIONS],
            proc_code="PROC-SA250-CHK", proc_title="Statutory Legal & Regulatory Compliance Review",
            proc_obj="Inspect regulatory communications, litigation registers, and tax assessment orders (SA 250.14).",
            proc_type="Compliance Review", proc_assertions=[AssertionEnum.COMPLETENESS],
            pop_def="Legal expense ledgers, tax notices, litigation registers, ROC secretarial filings.",
            meth_guide="100% review of legal fee payments and direct inquiry with company legal counsel.",
            evidence="Litigation register, tax demand notices, legal confirmation responses.",
            wp_ref="WP-SA250-STATUTORY-LAWS", wp_title="Legal & Regulatory Compliance Verification Schedule",
            wp_sections=[(1, "1. Legal Ledger Review", "Vouch payments to advocates and consultants."), (2, "2. Direct Inquiry", "Management representation on pending disputes.")],
            checklist=["Are all material tax and legal notices reviewed?", "Have contingent liabilities been disclosed?"],
        ),
        _build_sa_standard(
            code="SA 315", title="Identifying and Assessing the Risks of Material Misstatement",
            req_code="SA315-R1", req_title="Understanding Entity, Environment & Internal Control System",
            req_desc="Identify and assess risks of material misstatement at financial statement and assertion levels through understanding the entity.",
            rsk_code="RSK-SA315-CTRL", rsk_title="Control Deficiencies in Significant Financial Cycles", area="Internal Controls (ICFR)",
            rsk_level="HIGH", rsk_assertions=[AssertionEnum.OCCURRENCE, AssertionEnum.COMPLETENESS, AssertionEnum.ACCURACY],
            proc_code="PROC-SA315-WALK", proc_title="Business Process Walkthrough & Control Evaluation",
            proc_obj="Execute design and implementation walkthroughs across Revenue, Procurement, and Payroll cycles (SA 315.13).",
            proc_type="Test of Design (TOD)", proc_assertions=[AssertionEnum.OCCURRENCE, AssertionEnum.COMPLETENESS],
            pop_def="All standard transaction processing cycles and ERP controls.",
            meth_guide="Select 1 transaction per significant business cycle and trace initiation to GL posting.",
            evidence="Process flowcharts, SOP documents, signed walkthrough vouchers, IT access logs.",
            wp_ref="WP-SA315-ICFR-WALKTHROUGH", wp_title="Internal Financial Controls (ICFR) Walkthrough Working Paper",
            wp_sections=[(1, "1. Process Flow", "Document control initiation, approval, and recording."), (2, "2. Control Testing", "Evaluate segregation of duties and automated controls.")],
            checklist=["Are significant transaction cycles mapped?", "Has IT general control environment been evaluated?"],
        ),
        _build_sa_standard(
            code="SA 320", title="Materiality in Planning and Performing an Audit",
            req_code="SA320-R1", req_title="Determination of OM, PM and Clearly Trivial Thresholds",
            req_desc="Determine overall materiality, performance materiality, and clearly trivial threshold for planning audit scope.",
            rsk_code="RSK-SA320-MAT", rsk_title="Inappropriate Materiality Benchmark / Excessive Audit Risk", area="Audit Planning",
            rsk_level="HIGH", rsk_assertions=[AssertionEnum.ACCURACY, AssertionEnum.VALUATION],
            proc_code="PROC-SA320-CALC", proc_title="Deterministic Materiality Computation & Documentation",
            proc_obj="Calculate Overall Materiality, Performance Materiality (50-75%), and CTT (5%) from audited financial benchmarks (SA 320.10).",
            proc_type="Planning & Scope Definition", proc_assertions=[AssertionEnum.ACCURACY],
            pop_def="Preliminary or audited Revenue, Profit Before Tax, Total Assets, or Equity.",
            meth_guide="Apply deterministic decimal calculation with documented professional rationale.",
            evidence="Draft financial statements, benchmark rationale memo, partner approval record.",
            wp_ref="WP-SA320-MATERIALITY", wp_title="SA 320 Materiality Calculation & Planning Memorandum",
            wp_sections=[(1, "1. Benchmark Selection", "Document rationale for chosen benchmark."), (2, "2. Threshold Schedule", "Record OM, PM, and CTT in exact paise.")],
            checklist=["Has benchmark rationale been documented?", "Are performance materiality deductions justified?"],
        ),
        _build_sa_standard(
            code="SA 330", title="The Auditor's Responses to Assessed Risks",
            req_code="SA330-R1", req_title="Substantive Procedures Responsive to Assessed Risks",
            req_desc="Design and perform substantive procedures for each material class of transactions, account balance, and disclosure.",
            rsk_code="RSK-SA330-RESP", rsk_title="Substantive Testing Scope Insufficiency", area="Substantive Execution",
            rsk_level="HIGH", rsk_assertions=[AssertionEnum.EXISTENCE, AssertionEnum.COMPLETENESS, AssertionEnum.VALUATION],
            proc_code="PROC-SA330-SUBST", proc_title="Substantive Test of Details on Significant Balances",
            proc_obj="Perform substantive testing on account balances exceeding performance materiality (SA 330.18).",
            proc_type="Substantive Test of Details", proc_assertions=[AssertionEnum.EXISTENCE, AssertionEnum.VALUATION],
            pop_def="All account heads exceeding Performance Materiality.",
            meth_guide="Combine tests of controls with targeted substantive sampling and analytical reviews.",
            evidence="Supporting third-party vouchers, agreements, bank statements, ledger extractions.",
            wp_ref="WP-SA330-SUBSTANTIVE-RESP", wp_title="Substantive Audit Response & Testing Summary",
            wp_sections=[(1, "1. Risk Linkage", "Map assessed risk to specific procedure."), (2, "2. Test Execution", "Record sample testing results.")],
            checklist=["Are all assessed high risks covered by substantive tests?", "Are deviations investigated?"],
        ),
        _build_sa_standard(
            code="SA 450", title="Evaluation of Misstatements Identified during the Audit",
            req_code="SA450-R1", req_title="Accumulation and Evaluation of Identified Misstatements",
            req_desc="Accumulate misstatements identified during the audit, other than those that are clearly trivial.",
            rsk_code="RSK-SA450-MISST", rsk_title="Uncorrected Material Misstatements Altering Financial Truth", area="Audit Adjustments",
            rsk_level="CRITICAL", rsk_assertions=[AssertionEnum.ACCURACY, AssertionEnum.PRESENTATION],
            proc_code="PROC-SA450-EVAL", proc_title="Summary of Unadjusted Audit Differences (SUAD) Schedule",
            proc_obj="Accumulate and evaluate factual, judgmental, and projected misstatements against Overall Materiality (SA 450.5).",
            proc_type="Audit Completion & Evaluation", proc_assertions=[AssertionEnum.ACCURACY],
            pop_def="All audit exceptions and variance items exceeding Clearly Trivial Threshold.",
            meth_guide="Classify into corrected and uncorrected; evaluate aggregate impact on Net Profit and Equity.",
            evidence="Proposed adjustment entries, management communication letter, final SUAD schedule.",
            wp_ref="WP-SA450-MISSTATEMENTS", wp_title="Summary of Uncorrected Audit Misstatements Schedule",
            wp_sections=[(1, "1. Cumulative Misstatements", "Itemize all unadjusted differences."), (2, "2. Materiality Comparison", "Compare net impact against Overall Materiality.")],
            checklist=["Are all non-trivial misstatements accumulated?", "Does aggregate uncorrected misstatement exceed OM?"],
        ),
        _build_sa_standard(
            code="SA 500", title="Audit Evidence",
            req_code="SA500-R1", req_title="Sufficiency & Appropriateness of Audit Evidence",
            req_desc="Design and perform audit procedures to obtain sufficient appropriate audit evidence to be able to draw reasonable conclusions.",
            rsk_code="RSK-SA500-EVD", rsk_title="Unreliable / Insufficient Audit Evidence", area="Evidence Management",
            rsk_level="HIGH", rsk_assertions=[AssertionEnum.EXISTENCE, AssertionEnum.RIGHTS_AND_OBLIGATIONS],
            proc_code="PROC-SA500-VERIF", proc_title="Independent Source Evidence Corroboration",
            proc_obj="Verify authenticity, original electronic checksums, and third-party provenance of audit evidence (SA 500.7).",
            proc_type="Evidence Verification", proc_assertions=[AssertionEnum.EXISTENCE],
            pop_def="All evidentiary documents uploaded to working papers.",
            meth_guide="Verify SHA-256 integrity, inspect original tax portals, and evaluate management expert competence.",
            evidence="Original signed PDF documents, portal download logs, SHA-256 verification records.",
            wp_ref="WP-SA500-EVIDENCE-LOG", wp_title="Audit Evidence Sufficiency & Provenance Register",
            wp_sections=[(1, "1. Evidence Provenance", "Record source, author, and upload hash."), (2, "2. Reliability Assessment", "Evaluate internal vs external reliability.")],
            checklist=["Is evidence from independent sources where feasible?", "Are file SHA-256 hashes verified?"],
        ),
        _build_sa_standard(
            code="SA 505", title="External Confirmations",
            req_code="SA505-R1", req_title="Direct External Confirmation Procedures",
            req_desc="Maintain control over external confirmation requests including designing requests, selecting parties, and sending direct requests.",
            rsk_code="RSK-SA505-CONF", rsk_title="Fictitious Balances / Concealed Liabilities / Intercepted Letters", area="Debtors, Creditors & Banks",
            rsk_level="HIGH", rsk_assertions=[AssertionEnum.EXISTENCE, AssertionEnum.RIGHTS_AND_OBLIGATIONS, AssertionEnum.COMPLETENESS],
            proc_code="PROC-SA505-DIRECT", proc_title="Direct External Confirmation & Reconciliation Protocol",
            proc_obj="Send direct positive confirmation letters to Banks, Major Debtors, and Creditors under direct auditor control (SA 505.7).",
            proc_type="Substantive External Confirmation", proc_assertions=[AssertionEnum.EXISTENCE, AssertionEnum.COMPLETENESS],
            pop_def="All bank accounts, significant trade debtors (>5% total), and major trade payables.",
            meth_guide="Dispatch via auditor email/post; log tracking; perform alternative procedures for non-replies.",
            evidence="Signed confirmation letters, dispatch tracking receipts, reconciliation statements.",
            wp_ref="WP-SA505-CONFIRMATION-LOG", wp_title="External Confirmation Control & Variance Reconciliation Schedule",
            wp_sections=[(1, "1. Confirmation Control", "Log of accounts, dispatch dates, and responses."), (2, "2. Variance Reconciliation", "Reconcile differences between book and confirmed balances.")],
            checklist=["Were confirmations sent under auditor's direct control?", "Were alternative procedures performed on non-replies?"],
        ),
        _build_sa_standard(
            code="SA 510", title="Initial Audit Engagements — Opening Balances",
            req_code="SA510-R1", req_title="Opening Balances Verification & Accounting Policies Consistency",
            req_desc="Obtain sufficient appropriate audit evidence about whether opening balances contain misstatements materially affecting current period.",
            rsk_code="RSK-SA510-OPENING", rsk_title="Misstated Opening Balances / Inconsistent Accounting Policies", area="Opening Balances",
            rsk_level="HIGH", rsk_assertions=[AssertionEnum.COMPLETENESS, AssertionEnum.VALUATION, AssertionEnum.EXISTENCE],
            proc_code="PROC-SA510-TIE", proc_title="Opening Balance Tie-Out to Predecessor Auditor Report",
            proc_obj="Agree opening balances with audited closing figures of preceding period and test consistency of accounting policies (SA 510.6).",
            proc_type="Substantive Opening Tie-out", proc_assertions=[AssertionEnum.COMPLETENESS, AssertionEnum.ACCURACY],
            pop_def="All trial balance opening ledger accounts as at 1st April.",
            meth_guide="100% mathematical tie-out to signed prior year audited balance sheet and review of prior year working papers.",
            evidence="Predecessor auditor signed report, audited financial statements, opening journal vouchers.",
            wp_ref="WP-SA510-OPENING-BALANCES", wp_title="Opening Balances Verification & Prior Period Tie-Out Schedule",
            wp_sections=[(1, "1. Trial Balance Tie-Out", "Compare 1st April opening balances with prior year audited."), (2, "2. Policy Consistency", "Confirm no unapproved accounting policy changes.")],
            checklist=["Do opening balances tie 100% to audited prior year financials?", "Were predecessor auditor modifications reviewed?"],
        ),
        _build_sa_standard(
            code="SA 520", title="Analytical Procedures",
            req_code="SA520-R1", req_title="Substantive Analytical Procedures & Ratio Analysis",
            req_desc="Design and perform substantive analytical procedures and evaluate financial relationships against expectations.",
            rsk_code="RSK-SA520-ANALYTIC", rsk_title="Unexplained Fluctuations & Anomalous Financial Trends", area="Substantive Analytics",
            rsk_level="MEDIUM", rsk_assertions=[AssertionEnum.COMPLETENESS, AssertionEnum.ACCURACY, AssertionEnum.VALUATION],
            proc_code="PROC-SA520-TREND", proc_title="Multi-Period Financial Trend & Ratio Disaggregation",
            proc_obj="Compare current period revenues, margins, and key financial ratios against prior years and industry benchmarks (SA 520.5).",
            proc_type="Substantive Analytical Procedure", proc_assertions=[AssertionEnum.COMPLETENESS, AssertionEnum.ACCURACY],
            pop_def="Profit & Loss statement accounts and Balance Sheet line items across 3 historical periods.",
            meth_guide="Compute variance thresholds; investigate any monthly fluctuation >10% or exceeding PM.",
            evidence="Monthly revenue schedules, cost of goods sold reconciliations, gross margin reports.",
            wp_ref="WP-SA520-ANALYTICAL-REVIEW", wp_title="Substantive Analytical Procedures & Variance Analysis Working Paper",
            wp_sections=[(1, "1. Ratio Comparison", "Table of GP margin, Net margin, Current ratio, Debt-Equity."), (2, "2. Variance Inquiries", "Document management explanations and corroborating evidence.")],
            checklist=["Are expectations developed independently of client figures?", "Are significant variances corroborated by evidence?"],
        ),
        _build_sa_standard(
            code="SA 530", title="Audit Sampling",
            req_code="SA530-R1", req_title="Sample Design, Size and Selection of Items for Testing",
            req_desc="Determine a sample size sufficient to reduce sampling risk to an acceptably low level and select representative items.",
            rsk_code="RSK-SA530-SAMPLE", rsk_title="Sampling Bias / Inadequate Sample Size Failing to Detect Errors", area="Audit Sampling",
            rsk_level="HIGH", rsk_assertions=[AssertionEnum.ACCURACY, AssertionEnum.EXISTENCE, AssertionEnum.COMPLETENESS],
            proc_code="PROC-SA530-PLAN", proc_title="Statistical & Monetary Unit Sampling (MUS) Execution",
            proc_obj="Calculate sample sizes using MUS formula based on tolerable misstatement, risk of incorrect acceptance, and expected error (SA 530.7).",
            proc_type="Sampling Design & Execution", proc_assertions=[AssertionEnum.ACCURACY],
            pop_def="All substantive testing populations (Sales, Purchases, Fixed Asset Additions).",
            meth_guide="Apply deterministic formula: Interval = (TM - EM) / Reliability Factor; extract high-value items 100%.",
            evidence="Sampling plan output, random seed log, selected sample vouchers.",
            wp_ref="WP-SA530-SAMPLING-PLAN", wp_title="SA 530 Statistical Audit Sampling Plan & Sample Evaluation",
            wp_sections=[(1, "1. Parameter Definition", "Record population value, tolerable misstatement, and confidence level."), (2, "2. Sample Extraction", "List of selected items and original voucher numbers.")],
            checklist=["Was the sample size mathematically calculated?", "Were high-value items stratified for 100% inspection?"],
        ),
        _build_sa_standard(
            code="SA 560", title="Subsequent Events",
            req_code="SA560-R1", req_title="Events Occurring Between Balance Sheet Date and Auditor's Report Date",
            req_desc="Perform procedures to obtain evidence that all events occurring up to report date requiring adjustment or disclosure are identified.",
            rsk_code="RSK-SA560-EVENTS", rsk_title="Unrecorded Adjusting Events / Undisclosed Subsequent Catastrophes", area="Subsequent Events",
            rsk_level="HIGH", rsk_assertions=[AssertionEnum.VALUATION, AssertionEnum.PRESENTATION, AssertionEnum.COMPLETENESS],
            proc_code="PROC-SA560-POST", proc_title="Subsequent Period Bank, Legal & Board Minutes Review",
            proc_obj="Inspect bank statements, litigation outcomes, debtor recoveries, and board minutes up to date of audit report (SA 560.6).",
            proc_type="Substantive Subsequent Event Review", proc_assertions=[AssertionEnum.VALUATION, AssertionEnum.PRESENTATION],
            pop_def="All financial transactions, board minutes, and bank statements dated after balance sheet date up to audit report date.",
            meth_guide="100% review of board minutes and substantial post-close bank receipts and payments.",
            evidence="Subsequent board minutes, post-close bank statements, customer credit notes register.",
            wp_ref="WP-SA560-SUBSEQUENT-EVENTS", wp_title="SA 560 Subsequent Events Review Memorandum",
            wp_sections=[(1, "1. Minutes & Interim Accounts", "Review subsequent board meetings and financial reports."), (2, "2. Adjusting vs Non-Adjusting", "Classify identified events under AS 4 / Ind AS 10.")],
            checklist=["Are procedures performed up to the date of the audit report?", "Are material adjusting events reflected in the financial statements?"],
        ),
        _build_sa_standard(
            code="SA 570", title="Going Concern (Revised)",
            req_code="SA570-R1", req_title="Assessment of Management Going Concern Assumption & 12-Month Solvency",
            req_desc="Obtain evidence regarding appropriateness of management's use of going concern assumption and identify material uncertainties.",
            rsk_code="RSK-SA570-GC", rsk_title="Insolvency Risk / Negative Net Worth / Operating Cash Outflows", area="Going Concern",
            rsk_level="CRITICAL", rsk_assertions=[AssertionEnum.VALUATION, AssertionEnum.PRESENTATION],
            proc_code="PROC-SA570-CASH", proc_title="12-Month Look-Forward Cash Flow & Debt Repayment Assessment",
            proc_obj="Evaluate 12-month future cash flow forecasts, debt covenants, and management mitigating plans for feasibility (SA 570.16).",
            proc_type="Solvency & Going Concern Assessment", proc_assertions=[AssertionEnum.VALUATION, AssertionEnum.PRESENTATION],
            pop_def="12-month rolling cash flow forecast, bank sanction letters, loan repayment schedules.",
            meth_guide="Stress test revenue projections, challenge uncommitted financing, and review debt maturity covenants.",
            evidence="Management approved budget, bank credit limit sanction letters, net worth certificates.",
            wp_ref="WP-SA570-GOING-CONCERN", wp_title="SA 570 (Revised) Going Concern Assessment Memorandum",
            wp_sections=[(1, "1. Financial Indicator Review", "Evaluate net worth, working capital, and operating cashflows."), (2, "2. Auditor Conclusion", "Determine whether Material Uncertainty exists requiring report modification.")],
            checklist=["Has the 12-month look-forward period been evaluated?", "Is report disclosure or audit opinion modification required?"],
        ),
        _build_sa_standard(
            code="SA 580", title="Written Representations",
            req_code="SA580-R1", req_title="Management Representation Letter (MRL) Execution",
            req_desc="Obtain written representations from management and TCWG acknowledging responsibility for preparation of financial statements.",
            rsk_code="RSK-SA580-MRL", rsk_title="Refusal to Provide MRL / Disclaimer of Management Responsibility", area="Written Representations",
            rsk_level="CRITICAL", rsk_assertions=[AssertionEnum.COMPLETENESS, AssertionEnum.PRESENTATION],
            proc_code="PROC-SA580-OBTAIN", proc_title="Management Representation Letter (MRL) Tie-Out & Verification",
            proc_obj="Obtain signed Management Representation Letter dated matching the Auditor's Report Date (SA 580.14).",
            proc_type="Completion & Governance", proc_assertions=[AssertionEnum.COMPLETENESS],
            pop_def="Final draft of Management Representation Letter signed by CEO and CFO.",
            meth_guide="Verify inclusion of all standard clauses (irregularities, related parties, subsequent events, non-compliance).",
            evidence="Signed MRL on client letterhead, board resolution authorizing signatories.",
            wp_ref="WP-SA580-MRL", wp_title="Management Representation Letter (MRL) Audit Working Paper",
            wp_sections=[(1, "1. Signatory Authority", "Verify authorization under Board Resolution."), (2, "2. Date & Content Check", "Confirm date matches audit report date and covers all required clauses.")],
            checklist=["Is MRL dated on the same date as the independent audit report?", "Is it signed by authorized key management personnel?"],
        ),
        _build_sa_standard(
            code="SA 700", title="Forming an Opinion and Reporting on Financial Statements",
            req_code="SA700-R1", req_title="Auditor's Report Structure & True and Fair View Opinion",
            req_desc="Form an opinion on the financial statements based on an evaluation of conclusions drawn from audit evidence obtained.",
            rsk_code="RSK-SA700-OPINION", rsk_title="Defective Audit Report Structure / Non-Compliance with SA 700 Format", area="Audit Reporting",
            rsk_level="HIGH", rsk_assertions=[AssertionEnum.PRESENTATION],
            proc_code="PROC-SA700-DRAFT", proc_title="Audit Report Formulation & True and Fair Opinion Structuring",
            proc_obj="Structure independent auditor's report in accordance with SA 700 revised standard layout (SA 700.20).",
            proc_type="Audit Report Assembly", proc_assertions=[AssertionEnum.PRESENTATION],
            pop_def="Complete set of financial statements including notes and accounting policies.",
            meth_guide="Verify inclusion of Opinion, Basis for Opinion, Key Audit Matters (if SA 701 applicable), and Statutory CARO report.",
            evidence="Draft Independent Auditor's Report, partner signoff sheet, engagement quality review report.",
            wp_ref="WP-SA700-AUDIT-REPORT", wp_title="Independent Auditor's Report Formulation Schedule",
            wp_sections=[(1, "1. Opinion Formulation", "Document basis for unmodified or modified opinion."), (2, "2. Section Checklist", "Verify all statutory sections per Companies Act 2013 Sec 143.")],
            checklist=["Does the report follow the mandatory SA 700 structure?", "Are responsibilities of management and auditor clearly delineated?"],
        ),
        _build_sa_standard(
            code="SA 705", title="Modifications to the Opinion in the Independent Auditor's Report",
            req_code="SA705-R1", req_title="Determination of Qualified, Adverse, or Disclaimer of Opinion",
            req_desc="Issue modified opinion when financial statements are materially misstated or sufficient appropriate evidence cannot be obtained.",
            rsk_code="RSK-SA705-MOD", rsk_title="Improper Unmodified Opinion on Materially Misstated Accounts", area="Audit Reporting",
            rsk_level="CRITICAL", rsk_assertions=[AssertionEnum.PRESENTATION],
            proc_code="PROC-SA705-EVAL", proc_title="Materiality & Pervasiveness Matrix Evaluation",
            proc_obj="Evaluate whether misstatements/scope limitations are Material but Not Pervasive (Qualified) or Material and Pervasive (Adverse/Disclaimer) (SA 705.6).",
            proc_type="Reporting Decision Support", proc_assertions=[AssertionEnum.PRESENTATION],
            pop_def="All uncorrected misstatements, scope limitations, and non-compliance findings.",
            meth_guide="Apply deterministic 2x2 decision matrix: Materiality vs Pervasiveness.",
            evidence="Basis for Qualified/Adverse Opinion draft text, partner consultation minute.",
            wp_ref="WP-SA705-MODIFIED-OPINION", wp_title="SA 705 Opinion Modification Decision Memorandum",
            wp_sections=[(1, "1. Modification Basis", "Itemize quantified monetary impact of misstatement."), (2, "2. Pervasiveness Rationale", "Document rationale for Qualified vs Adverse vs Disclaimer.")],
            checklist=["Has the quantitative impact been clearly stated in Basis for Opinion?", "Has Partner and EQCR review been conducted?"],
        ),
        _build_sa_standard(
            code="SA 706", title="Emphasis of Matter Paragraphs and Other Matter Paragraphs",
            req_code="SA706-R1", req_title="Drafting Emphasis of Matter and Other Matter Disclosures",
            req_desc="Include Emphasis of Matter paragraph when matter is fundamental to users' understanding of financial statements.",
            rsk_code="RSK-SA706-EOM", rsk_title="Omission of Significant Matter Disclosures / Misuse of EoM as Substitute for Modification", area="Audit Reporting",
            rsk_level="HIGH", rsk_assertions=[AssertionEnum.PRESENTATION],
            proc_code="PROC-SA706-DRAFT", proc_title="Emphasis of Matter (EoM) Wording & Financial Statement Linkage",
            proc_obj="Draft EoM referring to specific Note in financial statements without modifying auditor's opinion (SA 706.7).",
            proc_type="Reporting Disclosure", proc_assertions=[AssertionEnum.PRESENTATION],
            pop_def="Significant litigation disclosures, regulatory events, major subsequent events.",
            meth_guide="Ensure EoM text explicitly references financial statement note and clarifies opinion is not modified in respect of this matter.",
            evidence="Referenced financial statement note, EoM draft wording.",
            wp_ref="WP-SA706-EOM-OM", wp_title="Emphasis of Matter (EoM) & Other Matter Working Paper",
            wp_sections=[(1, "1. EoM Subject Matter", "Document rationale and reference Note number."), (2, "2. Non-Modification Check", "Confirm opinion is unmodified regarding the matter.")],
            checklist=["Does EoM refer to a clear note in the financial statements?", "Does it state that the auditor's opinion is not modified?"],
        ),
    ]
