"""Authoritative Indian statutory compliance and regulatory framework methodology catalog."""

from finauditpro.domain.audit_matrix_entities import AssertionEnum
from finauditpro.domain.methodology_entities import (
    MethodologyProcedureTemplate,
    MethodologyRiskTemplate,
    StandardCategoryEnum,
    StandardDefinition,
    StandardRequirement,
)


def _build_statutory_standard(
    code: str, title: str, category: StandardCategoryEnum, authority: str,
    req_code: str, req_title: str, req_desc: str, stat_ref: str,
    rsk_code: str, rsk_title: str, area: str, rsk_level: str,
    rsk_assertions: list[AssertionEnum], proc_code: str, proc_title: str,
    proc_obj: str, proc_type: str, proc_assertions: list[AssertionEnum],
    pop_def: str, meth_guide: str, evidence: str, wp_ref: str, wp_title: str,
    wp_sections: list[tuple[int, str, str]], checklist: list[str],
) -> StandardDefinition:
    proc = MethodologyProcedureTemplate(
        procedure_code_prefix=proc_code, title=proc_title, objective=proc_obj,
        procedure_type=proc_type, assertions=proc_assertions, population_definition=pop_def,
        methodology_guidance=meth_guide, expected_evidence=evidence, working_paper_ref=wp_ref,
        working_paper_title=wp_title, wp_sections=wp_sections, review_checklist=checklist,
    )
    risk = MethodologyRiskTemplate(
        risk_code_prefix=rsk_code, risk_title=rsk_title, audit_area=area,
        inherent_risk_level=rsk_level, assertions=rsk_assertions, procedures=[proc],
    )
    req = StandardRequirement(
        requirement_code=req_code, title=req_title, description=req_desc,
        statutory_reference=stat_ref, risks=[risk],
    )
    return StandardDefinition(
        standard_code=code, title=title, category=category,
        authoritative_source=authority, effective_date="2021-04-01",
        requirements=[req],
    )


def get_statutory_standards_catalog() -> list[StandardDefinition]:
    """Return canonical catalog of Indian Statutory and Regulatory Standards."""
    return [
        _build_statutory_standard(
            code="Schedule III", title="Companies Act 2013 Schedule III Presentation & Disclosure",
            category=StandardCategoryEnum.COMPANIES_ACT_SCHEDULE_III, authority="Ministry of Corporate Affairs (MCA)",
            req_code="SCH3-REQ-01", req_title="Balance Sheet / P&L Presentation, Mandatory Ratios & Ageing Disclosures",
            req_desc="Present financial statements in accordance with Division I (AS) or Division II (Ind AS) including mandatory 11 key financial ratios, MSME ageing, CWIP ageing, and title deed disclosures.",
            stat_ref="Section 129 & Schedule III of Companies Act 2013",
            rsk_code="RSK-SCH3-NONCOMPL", rsk_title="Schedule III Non-Compliance & Misclassified Balances", area="Financial Statement Presentation",
            rsk_level="HIGH", rsk_assertions=[AssertionEnum.PRESENTATION, AssertionEnum.CLASSIFICATION],
            proc_code="PROC-SCH3-AUDIT", proc_title="Schedule III Classification & 11 Financial Ratios Audit",
            proc_obj="Verify Balance Sheet and P&L line classifications, Trade Payables/Receivables ageing, and compute 11 key ratios with explanations for variance >25%.",
            proc_type="Statutory Presentation Review", proc_assertions=[AssertionEnum.PRESENTATION, AssertionEnum.CLASSIFICATION],
            pop_def="Entire audited Balance Sheet, Statement of Profit and Loss, and Notes to Accounts.",
            meth_guide="100% verification against Schedule III Division I/II checklist and mathematical recalculation of all 11 statutory ratios.",
            evidence="Audited Financial Statements, Lead Schedules, Notes to Accounts, Statutory Ratio Calculation Sheet.",
            wp_ref="WP-SCH3-PRESENTATION", wp_title="Schedule III Presentation, Disclosures & Ratio Analysis Schedule",
            wp_sections=[(1, "1. Line Item Mapping", "Verify mapping of ledger accounts to Schedule III lines."), (2, "2. Ratio Analysis", "Recalculate 11 ratios and review explanations for >25% variance.")],
            checklist=["Are all 11 mandatory ratios computed and disclosed?", "Are ageing schedules provided for Trade Receivables, Payables, CWIP, and Intangibles under development?"],
        ),
        _build_statutory_standard(
            code="CARO 2020", title="Companies (Auditor's Report) Order, 2020",
            category=StandardCategoryEnum.CARO_2020, authority="Ministry of Corporate Affairs (MCA)",
            req_code="CARO-REQ-01", req_title="Clauses 3(i) to 3(xxi) Statutory Reporting Verification",
            req_desc="Report on all 21 specific matters under CARO 2020 including PPE physical verification, title deeds, inventory count, working capital limits >5 Cr, Benami property, defaults, statutory dues, and whistle-blower complaints.",
            stat_ref="Section 143(11) of Companies Act 2013 / CARO 2020 Order",
            rsk_code="RSK-CARO-REPORT", rsk_title="Omission of Mandatory CARO 2020 Adverse Disclosures", area="CARO Statutory Reporting",
            rsk_level="CRITICAL", rsk_assertions=[AssertionEnum.PRESENTATION, AssertionEnum.COMPLETENESS],
            proc_code="PROC-CARO-EVAL", proc_title="CARO 2020 Clauses 3(i) to 3(xxi) Comprehensive Evaluation",
            proc_obj="Execute structured audit inquiry across all 21 clauses of CARO 2020 and formulate clause-by-clause audit reporting remarks.",
            proc_type="CARO Statutory Audit", proc_assertions=[AssertionEnum.PRESENTATION, AssertionEnum.COMPLETENESS],
            pop_def="All fixed assets, inventories, bank sanction letters, loan registers, statutory dues registers.",
            meth_guide="Verify physical verification records, examine quarterly returns to banks against books, and check for Benami proceedings.",
            evidence="Fixed asset register, physical inventory count sheets, quarterly bank stock statements, ROC search reports.",
            wp_ref="WP-CARO2020-CHECKLIST", wp_title="CARO 2020 Audit Verification & Clause-by-Clause Reporting Schedule",
            wp_sections=[(1, "1. Clause 3(i)-3(v) Asset & Loan Checks", "Document PPE, inventory, and Section 185/186 loan checks."), (2, "2. Clause 3(vii)-3(xxi) Statutory & Financial Stability", "Document statutory dues, irregularities, and financial stability.")],
            checklist=["Have quarterly returns submitted to banks been reconciled with books (Clause 3(ii)(b))?", "Has physical verification of PPE and inventory been confirmed?"],
        ),
        _build_statutory_standard(
            code="GST Compliance", title="Goods and Services Tax (GST) Statutory Audit & ITC Verification",
            category=StandardCategoryEnum.TAXATION_GST, authority="Central Board of Indirect Taxes and Customs (CBIC)",
            req_code="GST-REQ-01", req_title="Input Tax Credit (ITC) Eligibility & GSTR-2B vs Books Reconciliation",
            req_desc="Verify that Input Tax Credit claimed conforms to Section 16(2)(aa) matching with GSTR-2B, blocked credits under Section 17(5) are reversed, and turnover in GSTR-1/3B reconciles with audited books.",
            stat_ref="CGST Act 2017 Sections 16, 17, 35(5), 44 & Rules 36(4), 88B",
            rsk_code="RSK-GST-ITC", rsk_title="Ineligible ITC Claims / Unreconciled Turnover / Interest & Penalties", area="Indirect Taxes (GST)",
            rsk_level="HIGH", rsk_assertions=[AssertionEnum.ACCURACY, AssertionEnum.COMPLETENESS, AssertionEnum.RIGHTS_AND_OBLIGATIONS],
            proc_code="PROC-GST-RECON", proc_title="GST Books vs GSTR-1, GSTR-3B & GSTR-2B 3-Way Reconciliation",
            proc_obj="Execute deterministic 3-way reconciliation between general ledger tax registers, GSTR-1 sales, GSTR-3B filed tax, and GSTR-2B eligible ITC.",
            proc_type="Tax Compliance & Substantive Tie-Out", proc_assertions=[AssertionEnum.ACCURACY, AssertionEnum.COMPLETENESS],
            pop_def="Full year General Ledger Sales and Purchase registers and monthly GSTR-1, 3B, and 2B returns.",
            meth_guide="Automated 100% invoice matching on GSTIN and invoice numbers; verify Section 17(5) motor vehicle and personal consumption reversals.",
            evidence="GSTR-1, 3B, 2B JSON extracts, Purchase Register, Sales Register, GST Annual Return GSTR-9.",
            wp_ref="WP-TAX-GST-RECON", wp_title="GST Annual Reconciliation & Input Tax Credit Verification Schedule",
            wp_sections=[(1, "1. Turnover Reconciliation", "Reconcile Books Turnover vs GSTR-1 vs GSTR-3B."), (2, "2. ITC Matching", "Detail 2B vs Books ITC variances and Section 17(5) reversals.")],
            checklist=["Does GSTR-3B turnover reconcile with audited revenue?", "Are ITC claims restricted to invoices appearing in GSTR-2B?"],
        ),
        _build_statutory_standard(
            code="TDS Compliance", title="Income Tax Tax Deducted at Source (TDS/TCS) Audit",
            category=StandardCategoryEnum.TAXATION_TDS, authority="Central Board of Direct Taxes (CBDT)",
            req_code="TDS-REQ-01", req_title="Deduction, Deposit & Section 40(a)(ia) Expense Disallowance",
            req_desc="Verify deduction of TDS under Chapter XVII-B (Sections 194C, 194J, 194I, 194H, 194Q), timely deposit before due dates, and 30% expense disallowance under Section 40(a)(ia) for non-deduction/non-payment.",
            stat_ref="Income Tax Act, 1961 Chapter XVII-B & Section 40(a)(ia), 206AB",
            rsk_code="RSK-TDS-NONDEP", rsk_title="Omission of TDS / Interest Under 201(1A) / 30% Expense Disallowance", area="Direct Taxes (TDS)",
            rsk_level="HIGH", rsk_assertions=[AssertionEnum.COMPLETENESS, AssertionEnum.ACCURACY],
            proc_code="PROC-TDS-AUDIT", proc_title="TDS Expense-Wise Applicability & Form 26Q/27Q Reconciliation",
            proc_obj="Audit expenditure ledger heads against applicable TDS thresholds, verify deduction rates, and reconcile with Form 26Q quarterly returns.",
            proc_type="Direct Tax Compliance Audit", proc_assertions=[AssertionEnum.COMPLETENESS, AssertionEnum.ACCURACY],
            pop_def="Contractor, professional fee, rent, commission, and high-value purchase expenditure accounts.",
            meth_guide="Sample expenditure vouchers exceeding threshold limits; cross-verify challan payment dates against statutory due dates.",
            evidence="Quarterly Form 26Q/27Q acknowledgments, TDS challans, Form 16A certificates, Form 26AS/AIS.",
            wp_ref="WP-TAX-TDS-3CD", wp_title="TDS Compliance, Deductions & Form 3CD Clause 34 Schedule",
            wp_sections=[(1, "1. Rate Applicability", "Verify threshold limits and rates under Sec 194C, 194J, 194Q."), (2, "2. Timely Deposit", "Check challan dates and compute Sec 201(1A) interest if delayed.")],
            checklist=["Has 30% expense disallowance been applied for un-deducted/un-deposited TDS?", "Are PAN and 206AB higher-rate deductions verified?"],
        ),
        _build_statutory_standard(
            code="MCA Checks", title="MCA Secretarial, Statutory Registers & Disqualification Checks",
            category=StandardCategoryEnum.MCA_SECRETARIAL, authority="Ministry of Corporate Affairs (MCA)",
            req_code="MCA-REQ-01", req_title="ROC Filing Compliance, Director Disqualification & Section 185/186 Loans",
            req_desc="Verify timely filing of annual financial statements (AOC-4) and annual returns (MGT-7), check Director DIN status under Section 164(2), and verify compliance with Section 185/186 loan and investment restrictions.",
            stat_ref="Companies Act 2013 Sections 92, 137, 164(2), 185, 186",
            rsk_code="RSK-MCA-ROC", rsk_title="Director Disqualification / Prohibited Loans to Directors / Penalties", area="Corporate Governance & Secretarial",
            rsk_level="HIGH", rsk_assertions=[AssertionEnum.RIGHTS_AND_OBLIGATIONS, AssertionEnum.PRESENTATION],
            proc_code="PROC-MCA-VERIF", proc_title="ROC Master Data, DIN Status & Section 185/186 Verification",
            proc_obj="Inspect MCA portal master data, check DIN active status of all directors, and verify compliance with loan to director restrictions.",
            proc_type="Secretarial & Regulatory Verification", proc_assertions=[AssertionEnum.RIGHTS_AND_OBLIGATIONS],
            pop_def="MCA portal company master data, Director master list, loan and guarantee registers.",
            meth_guide="Direct portal query on MCA portal for DIN status, charges registered, and filed forms.",
            evidence="MCA master data extract, DIN status verification screenshot, signed Form MBP-1 declarations.",
            wp_ref="WP-MCA-ROC-CHECKS", wp_title="MCA Secretarial, Director Disqualification & Statutory Registers Schedule",
            wp_sections=[(1, "1. Master Data & Charges", "Verify registered charges against bank loan sanction letters."), (2, "2. Director Compliance", "Confirm DIN active status and absence of disqualification under Sec 164(2).")],
            checklist=["Are all director DINs active and compliant under Section 164(2)?", "Are loans to directors and investments compliant with Sections 185 and 186?"],
        ),
        _build_statutory_standard(
            code="Related Parties Sec 188", title="Related Party Disclosures, Contracts & Section 188 Compliance",
            category=StandardCategoryEnum.RELATED_PARTIES_SEC188, authority="MCA & ICAI (AS 18 / Ind AS 24 / SA 550)",
            req_code="RP-REQ-01", req_title="Section 188 Approvals, Arm's Length Pricing & Accounting Disclosures",
            req_desc="Identify all related party transactions, verify prior Audit Committee approval, Board resolution, and shareholder approval where transaction exceeds 10% statutory turnover threshold; verify arm's length pricing.",
            stat_ref="Section 188, 177, 184 of Companies Act 2013 & AS 18 / Ind AS 24 / SA 550",
            rsk_code="RSK-RP-UNDISCLOSED", rsk_title="Undisclosed Related Parties / Non-Arm's Length Siphoning / Unapproved Contracts", area="Related Party Transactions",
            rsk_level="CRITICAL", rsk_assertions=[AssertionEnum.OCCURRENCE, AssertionEnum.COMPLETENESS, AssertionEnum.ACCURACY, AssertionEnum.PRESENTATION],
            proc_code="PROC-RP-AUDIT", proc_title="Related Party Identification, Ledger Scan & Section 188 Verification",
            proc_obj="Scan general ledger against KMP/Director declarations (Form MBP-1), test arm's length benchmarking, and verify Audit Committee omnibus approvals.",
            proc_type="Substantive Related Party Audit", proc_assertions=[AssertionEnum.OCCURRENCE, AssertionEnum.COMPLETENESS, AssertionEnum.PRESENTATION],
            pop_def="All declared related parties, Director Form MBP-1 entries, and related ledger accounts.",
            meth_guide="100% scan of transactions with related entities; examine transfer pricing documentation and contract price comparisons.",
            evidence="Form MBP-1, Register of Contracts (Form MBP-4), Audit Committee minutes, Transfer Pricing Study.",
            wp_ref="WP-RP-SECTION188", wp_title="Related Party Transactions, Section 188 Compliance & AS 18 Schedule",
            wp_sections=[(1, "1. Related Party Master", "Complete list of related parties per Sec 2(76) and Ind AS 24."), (2, "2. Transaction Audit", "Vouch transactions for arm's length pricing and statutory approvals.")],
            checklist=["Have all related party transactions received prior Audit Committee approval?", "Are transactions exceeding statutory limits approved by special resolution?"],
        ),
        _build_statutory_standard(
            code="Statutory Compliance", title="Labor Laws, EPF, ESIC, Gratuity & MSMED Act Compliance",
            category=StandardCategoryEnum.STATUTORY_COMPLIANCE, authority="Ministry of Labour & Employment / Ministry of MSME",
            req_code="STAT-REQ-01", req_title="Statutory Labor Dues Timely Deposit & MSME 45-Day Payment Rule",
            req_desc="Verify timely deposit of Employee Provident Fund (EPF), ESI, and Professional Tax before the 15th of the following month, verify actuarial valuation for Gratuity (AS 15 / Ind AS 19), and verify payment to MSME vendors within 45 days under Section 43B(h).",
            stat_ref="EPF Act 1952, ESI Act 1948, MSMED Act 2006 Sec 15/16, Income Tax Act Sec 43B(h)",
            rsk_code="RSK-STAT-DUES", rsk_title="Default in Depositing Employee Contributions / Disallowance Under Sec 43B(h)", area="Payroll & Statutory Liabilities",
            rsk_level="HIGH", rsk_assertions=[AssertionEnum.COMPLETENESS, AssertionEnum.CUT_OFF, AssertionEnum.RIGHTS_AND_OBLIGATIONS],
            proc_code="PROC-STAT-AUDIT", proc_title="Statutory Challan Audit, Actuarial Review & MSME Ageing Tie-Out",
            proc_obj="Audit monthly PF/ESI electronic challan receipts, verify timely deposit of employee share (disallowed if late under Sec 36(1)(va)), and test MSME vendor payments within 45 days.",
            proc_type="Statutory Compliance Audit", proc_assertions=[AssertionEnum.COMPLETENESS, AssertionEnum.ACCURACY],
            pop_def="Monthly payroll registers, statutory dues challans, trade payables MSME sub-ledger.",
            meth_guide="100% verification of challan deposit dates; match MSME registration certificates (Udyam) with payment dates.",
            evidence="EPF ECR Challans, ESIC Challans, Actuarial Valuation Certificate, MSME Udyam Certificates.",
            wp_ref="WP-STAT-DUES-MSME", wp_title="Statutory Dues, PF/ESI Timely Deposit & MSME Section 43B(h) Working Paper",
            wp_sections=[(1, "1. PF / ESI Challan Log", "Month-wise table of wages, deduction, and challan deposit date."), (2, "2. MSME 45-Day Rule", "Identify overdue payments to MSME enterprises and compute Section 43B(h) disallowance.")],
            checklist=["Were employee PF/ESI contributions deposited before the statutory due date?", "Have payments to micro and small enterprises beyond 45 days been disallowed under Section 43B(h)?"],
        ),
    ]
