"""Pure rendering helpers for report artifacts."""

import os
import tempfile
from pathlib import Path
from typing import Any

_MPL_CONFIG_DIR = Path(tempfile.gettempdir()) / "finauditpro_matplotlib_config"
_MPL_CONFIG_DIR.mkdir(parents=True, exist_ok=True)
os.environ["MPLCONFIGDIR"] = str(_MPL_CONFIG_DIR)

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.platypus import Image as RLImage
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from finauditpro.domain.export_sanitizer import escape_formula_injection
from finauditpro.domain.report_entities import Report


class WatermarkedCanvas(canvas.Canvas):
    """Draw a prominent watermark on draft reports."""

    def __init__(self, *args: Any, is_draft: bool = True, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.is_draft = is_draft

    def showPage(self) -> None:
        if self.is_draft:
            self.saveState()
            self.setFont("Helvetica-Bold", 48)
            self.setFillColor(colors.Color(0.9, 0.2, 0.2, alpha=0.18))
            self.translate(300, 400)
            self.rotate(45)
            self.drawCentredString(0, 0, "DRAFT — NOT FOR ISSUANCE")
            self.restoreState()
        super().showPage()


def _generate_chart(findings: list[dict[str, Any]], chart_path: Path) -> None:
    counts = {"HIGH": 0, "MEDIUM": 0, "LOW": 0}
    for finding in findings:
        counts[
            finding["severity"].upper() if finding["severity"].upper() in counts else "MEDIUM"
        ] += 1
    plt.figure(figsize=(5, 3))
    plt.bar(list(counts), list(counts.values()), color=["#ef4444", "#f59e0b", "#10b981"])
    plt.title("Audit Findings by Severity", fontsize=10, fontweight="bold")
    plt.ylabel("Count")
    plt.tight_layout()
    plt.savefig(chart_path, dpi=150)
    plt.close()


def render_pdf(report: Report, data: dict[str, Any], pdf_path: Path, is_draft: bool) -> None:
    """Render a PDF from supplied report data without performing database access."""
    doc = SimpleDocTemplate(
        str(pdf_path), pagesize=letter, leftMargin=36, rightMargin=36, topMargin=36, bottomMargin=36
    )
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "TitleStyle",
        parent=styles["Heading1"],
        fontSize=18,
        leading=22,
        textColor=colors.HexColor("#1e293b"),
    )
    story = [Paragraph(f"<b>FinAuditPro — {report.title}</b>", title_style), Spacer(1, 10)]
    story.append(
        Paragraph(
            f"<b>Data As-Of:</b> {data['as_of']} | <b>Generated By:</b> {report.generated_by}",
            styles["Normal"],
        )
    )
    story.append(Spacer(1, 15))
    chart_path = pdf_path.with_suffix(".chart.png")
    _generate_chart(data["findings"], chart_path)
    if chart_path.exists():
        story.extend([RLImage(chart_path, width=4 * inch, height=2.4 * inch), Spacer(1, 15)])
    story.append(Paragraph("<b>Accepted Audit Findings Summary</b>", styles["Heading2"]))
    rows = [["Title", "Severity", "Status", "Amount (Paise)", "AI Source"]]
    rows.extend(
        [
            [
                escape_formula_injection(item["title"]),
                escape_formula_injection(item["severity"]),
                escape_formula_injection(item["status"]),
                str(item["amount_paise"]),
                "[AI ASSISTED]" if item.get("is_ai_generated") else "Deterministic",
            ]
            for item in data["findings"]
        ]
    )
    if len(rows) == 1:
        rows.append(["No findings recorded.", "-", "-", "-", "-"])
    table = Table(rows, colWidths=[2.2 * inch, inch, inch, 1.2 * inch, 1.2 * inch])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f172a")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
            ]
        )
    )
    story.append(table)
    doc.build(
        story,
        canvasmaker=lambda *args, **kwargs: WatermarkedCanvas(*args, is_draft=is_draft, **kwargs),
    )
    chart_path.unlink(missing_ok=True)
