"""
Primary Reporting & Export Workspace View for FinAuditPro.
Assembly wizard, draft watermarking, and formula-injection-safe XLSX/CSV export.
"""
from typing import Any

from PySide6.QtCore import Signal
from PySide6.QtWidgets import (
    QHBoxLayout,
    QHeaderView,
    QMessageBox,
    QPushButton,
    QTableWidget,
    QTableWidgetItem,
    QVBoxLayout,
    QWidget,
)

from finauditpro.application.report_dtos import ApproveReportDTO, ExportReportDTO
from finauditpro.application.services.engagement_service import EngagementService
from finauditpro.application.services.report_service import ReportService
from finauditpro.domain.entities import Engagement
from finauditpro.domain.report_entities import ExportFormatEnum, ReportStatusEnum
from finauditpro.ui.dialogs.report_wizard_dialog import ReportWizardDialog
from finauditpro.ui.theme import CardWidget, EmptyStateWidget, MetricCard, PageHeader


class ReportView(QWidget):
    """Primary Reporting & Safe Export Workspace View."""

    report_changed = Signal()

    def __init__(
        self,
        engagement_service: EngagementService,
        report_service: ReportService,
        parent: QWidget | None = None,
    ) -> None:
        super().__init__(parent)
        self.engagement_service = engagement_service
        self.report_service = report_service
        self.current_engagement: Engagement | None = None

        self._init_ui()

    def _init_ui(self) -> None:
        layout = QVBoxLayout(self)
        layout.setContentsMargins(24, 20, 24, 24)
        layout.setSpacing(14)

        # 1. Page Header
        self.header = PageHeader(
            title="Reports & Assembly",
            subtitle="Generate statutory audit reports, CARO disclosures, and formula-injection-safe XLSX/CSV files.",
            action_text="+ Generate Report",
            action_callback=self._on_generate_wizard_clicked,
        )
        layout.addWidget(self.header)

        # 2. Metric Summary Cards
        summary_layout = QHBoxLayout()
        summary_layout.setSpacing(10)
        self.card_total = MetricCard(
            "TOTAL REPORTS", "0", "Generated files", accent_color="#2563EB"
        )
        self.card_drafts = MetricCard(
            "DRAFT (WATERMARKED)", "0", "Awaiting partner signoff", accent_color="#D97706"
        )
        self.card_approved = MetricCard(
            "APPROVED REPORTS", "0", "Finalized statutory files", accent_color="#16A34A"
        )

        summary_layout.addWidget(self.card_total)
        summary_layout.addWidget(self.card_drafts)
        summary_layout.addWidget(self.card_approved)
        layout.addLayout(summary_layout)

        # 3. Table Card & Empty State
        self.table_card = CardWidget("GENERATED STATUTORY REPORTS")
        self.table = QTableWidget()
        self.table.setColumnCount(7)
        self.table.setHorizontalHeaderLabels(
            [
                "REPORT TITLE",
                "TYPE",
                "STATUS",
                "DATA AS-OF",
                "GENERATED BY",
                "CONTENT HASH",
                "ACTIONS",
            ]
        )
        self.table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.Stretch)
        for c in range(1, 7):
            self.table.horizontalHeader().setSectionResizeMode(
                c, QHeaderView.ResizeMode.ResizeToContents
            )
        self.table.verticalHeader().setVisible(False)
        self.table.setAlternatingRowColors(True)

        self.empty_state = EmptyStateWidget(
            title="No statutory reports generated yet",
            description="Generate audit reports from templates, including independent auditor's report and CARO 2020 annexures.",
            action_text="+ Generate Report",
            action_callback=self._on_generate_wizard_clicked,
        )

        self.table_card.content_layout.addWidget(self.table)
        self.table_card.content_layout.addWidget(self.empty_state)
        layout.addWidget(self.table_card)
        layout.addStretch(1)

        self.refresh()

    def set_engagement(self, engagement: Any) -> None:
        if isinstance(engagement, Engagement):
            self.current_engagement = engagement
            self.header.action_btn.setEnabled(True)
        elif engagement:
            try:
                self.current_engagement = self.engagement_service.get_engagement(str(engagement))
                self.header.action_btn.setEnabled(True)
            except Exception:
                self.current_engagement = None
                self.header.action_btn.setEnabled(False)
        else:
            self.current_engagement = None
            self.header.action_btn.setEnabled(False)
        self.refresh()

    set_active_engagement = set_engagement


    def refresh(self) -> None:
        if not self.current_engagement:
            self.table.setVisible(False)
            self.empty_state.setVisible(True)
            self.card_total.set_value("0")
            self.card_drafts.set_value("0")
            self.card_approved.set_value("0")
            return

        reports = self.report_service.list_reports(self.current_engagement.id)
        if not reports:
            self.table.setVisible(False)
            self.empty_state.setVisible(True)
            self.card_total.set_value("0")
            self.card_drafts.set_value("0")
            self.card_approved.set_value("0")
            return

        self.table.setVisible(True)
        self.empty_state.setVisible(False)
        self.table.setRowCount(0)

        draft_count = 0
        approved_count = 0

        for r, rep in enumerate(reports):
            self.table.insertRow(r)
            if rep.status == ReportStatusEnum.DRAFT:
                draft_count += 1
            elif rep.status == ReportStatusEnum.APPROVED:
                approved_count += 1

            self.table.setItem(r, 0, QTableWidgetItem(rep.title))
            self.table.setItem(r, 1, QTableWidgetItem(rep.report_type.value))
            self.table.setItem(r, 2, QTableWidgetItem(f"● {rep.status.value}"))
            self.table.setItem(r, 3, QTableWidgetItem(rep.data_as_of[:10]))
            self.table.setItem(r, 4, QTableWidgetItem(rep.generated_by))
            self.table.setItem(r, 5, QTableWidgetItem(f"{rep.content_hash[:8]}..."))

            act_widget = QWidget()
            act_layout = QHBoxLayout(act_widget)
            act_layout.setContentsMargins(2, 2, 2, 2)
            act_layout.setSpacing(4)

            btn_approve = QPushButton("Approve")
            btn_approve.setEnabled(rep.status != ReportStatusEnum.APPROVED)
            btn_approve.clicked.connect(lambda _, rid=rep.id: self._approve_report(rid))

            btn_xlsx = QPushButton("XLSX")
            btn_xlsx.clicked.connect(lambda _, rid=rep.id: self._export_xlsx(rid))

            btn_csv = QPushButton("CSV")
            btn_csv.clicked.connect(lambda _, rid=rep.id: self._export_csv(rid))

            act_layout.addWidget(btn_approve)
            act_layout.addWidget(btn_xlsx)
            act_layout.addWidget(btn_csv)
            self.table.setCellWidget(r, 6, act_widget)

        self.table.setFixedHeight(max(1, len(reports)) * 36 + 32)
        self.card_total.set_value(str(len(reports)))
        self.card_drafts.set_value(str(draft_count))
        self.card_approved.set_value(str(approved_count))

    def _on_generate_wizard_clicked(self) -> None:
        if not self.current_engagement:
            QMessageBox.warning(
                self, "No Engagement", "Please select an active audit engagement first."
            )
            return

        dlg = ReportWizardDialog(self.current_engagement.id, self.report_service, parent=self)
        if dlg.exec():
            self.refresh()
            self.report_changed.emit()

    def _approve_report(self, report_id: str) -> None:
        res = QMessageBox.question(
            self,
            "Confirm Report Approval",
            "Approve report and remove 'DRAFT' watermark?\n\nNotice: Approval is an internal workflow attestation.",
            QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No,
        )
        if res == QMessageBox.StandardButton.Yes:
            self.report_service.approve_report(
                ApproveReportDTO(
                    report_id=report_id, approved_by="Audit Partner", approver_role="Partner"
                )
            )
            QMessageBox.information(
                self, "Report Approved", "Report approved! Watermark removed from PDF."
            )
            self.refresh()
            self.report_changed.emit()

    def _export_xlsx(self, report_id: str) -> None:
        path = self.report_service.export_to_xlsx(
            ExportReportDTO(report_id=report_id, export_format=ExportFormatEnum.XLSX)
        )
        QMessageBox.information(
            self, "XLSX Exported", f"Successfully exported formula-escaped XLSX to:\n{path}"
        )

    def _export_csv(self, report_id: str) -> None:
        path = self.report_service.export_to_csv(
            ExportReportDTO(report_id=report_id, export_format=ExportFormatEnum.CSV)
        )
        QMessageBox.information(
            self, "CSV Exported", f"Successfully exported formula-escaped CSV to:\n{path}"
        )
