"""Primary Reporting & Export Workspace View for FinAuditPro."""

from PySide6.QtCore import Signal
from PySide6.QtWidgets import (
    QHBoxLayout,
    QHeaderView,
    QLabel,
    QMessageBox,
    QPushButton,
    QTableWidget,
    QTableWidgetItem,
    QVBoxLayout,
    QWidget,
)

from finauditpro.application.report_dtos import ApproveReportDTO, ExportReportDTO
from finauditpro.application.services.engagement_service import EngagementService
from finauditpro.application.services.report_service import ReportService
from finauditpro.domain.entities import Engagement
from finauditpro.domain.report_entities import ExportFormatEnum, ReportStatusEnum
from finauditpro.ui.dialogs.report_wizard_dialog import ReportWizardDialog
from finauditpro.ui.theme import CardWidget, MetricCard


class ReportView(QWidget):
    """Primary Reporting & Safe Export Workspace View."""

    report_changed = Signal()

    def __init__(
        self,
        engagement_service: EngagementService,
        report_service: ReportService,
        parent: QWidget | None = None,
    ) -> None:
        super().__init__(parent)
        self.engagement_service = engagement_service
        self.report_service = report_service
        self.current_engagement: Engagement | None = None

        self._init_ui()

    def _init_ui(self) -> None:
        layout = QVBoxLayout(self)
        layout.setContentsMargins(20, 20, 20, 20)
        layout.setSpacing(14)

        # 1. Header Row
        header = QHBoxLayout()
        title = QLabel("Reporting, Assembly & Injection-Safe Export Workspace")
        title.setStyleSheet("font-size: 18px; font-weight: 800; color: #f8fafc;")
        header.addWidget(title)
        header.addStretch()

        btn_generate = QPushButton("+ Generate New Report")
        btn_generate.setStyleSheet("background-color: #3b82f6; color: white; font-weight: bold;")
        btn_generate.clicked.connect(self._on_generate_wizard_clicked)
        header.addWidget(btn_generate)
        layout.addLayout(header)

        # 2. Disclaimer Guidance Card
        guidance_card = CardWidget("Statutory Report Text & Legal Signature Honesty")
        disc_lbl = QLabel(
            "<b>Statutory Opinion Notice:</b> Statutory auditor's reports and CARO formats are auditor-supplied "
            "templates carrying <code>verified_statutory: False</code>.<br>"
            "<b>Export Security:</b> All XLSX/CSV export paths enforce formula-injection escaping "
            "(<code>'</code> prefix for <code>=</code>, <code>+</code>, <code>-</code>, <code>@</code>, <code>\\t</code>, <code>\\r</code>).<br>"
            "<b>Sign-off Disclaimer:</b> Report approval is an internal workflow attestation, <b>NOT</b> an IT Act 2000 Class 3 PKI DSC."
        )
        disc_lbl.setStyleSheet("font-size: 11px; color: #94a3b8;")
        guidance_card.content_layout.addWidget(disc_lbl)
        layout.addWidget(guidance_card)

        # 3. Metric Summary Cards
        summary_layout = QHBoxLayout()
        self.card_total = MetricCard("Total Reports", "0")
        self.card_drafts = MetricCard("Draft Reports (Watermarked)", "0")
        self.card_approved = MetricCard("Approved Reports", "0")

        summary_layout.addWidget(self.card_total)
        summary_layout.addWidget(self.card_drafts)
        summary_layout.addWidget(self.card_approved)
        layout.addLayout(summary_layout)

        # 4. Table Widget
        self.table = QTableWidget()
        self.table.setColumnCount(7)
        self.table.setHorizontalHeaderLabels(
            [
                "Report Title",
                "Type",
                "Status",
                "Data As-Of",
                "Generated By",
                "Content Hash",
                "Actions",
            ]
        )
        self.table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Stretch)
        layout.addWidget(self.table)

        self.refresh()

    def set_engagement(self, engagement_id: str | None) -> None:
        if engagement_id:
            try:
                self.current_engagement = self.engagement_service.get_engagement(engagement_id)
            except Exception:
                self.current_engagement = None
        else:
            self.current_engagement = None
        self.refresh()

    def refresh(self) -> None:
        if not self.current_engagement:
            self.table.setRowCount(0)
            self.card_total.set_value("0")
            self.card_drafts.set_value("0")
            self.card_approved.set_value("0")
            return

        reports = self.report_service.list_reports(self.current_engagement.id)

        self.table.setRowCount(0)
        draft_count = 0
        approved_count = 0

        for r, rep in enumerate(reports):
            self.table.insertRow(r)
            if rep.status == ReportStatusEnum.DRAFT:
                draft_count += 1
            elif rep.status == ReportStatusEnum.APPROVED:
                approved_count += 1

            self.table.setItem(r, 0, QTableWidgetItem(rep.title))
            self.table.setItem(r, 1, QTableWidgetItem(rep.report_type.value))
            self.table.setItem(r, 2, QTableWidgetItem(rep.status.value))
            self.table.setItem(r, 3, QTableWidgetItem(rep.data_as_of[:10]))
            self.table.setItem(r, 4, QTableWidgetItem(rep.generated_by))
            self.table.setItem(r, 5, QTableWidgetItem(f"{rep.content_hash[:8]}..."))

            # Action Buttons Panel
            act_widget = QWidget()
            act_layout = QHBoxLayout(act_widget)
            act_layout.setContentsMargins(2, 2, 2, 2)

            btn_approve = QPushButton("Approve")
            btn_approve.setEnabled(rep.status != ReportStatusEnum.APPROVED)
            btn_approve.clicked.connect(lambda _, rid=rep.id: self._approve_report(rid))

            btn_xlsx = QPushButton("XLSX")
            btn_xlsx.clicked.connect(lambda _, rid=rep.id: self._export_xlsx(rid))

            btn_csv = QPushButton("CSV")
            btn_csv.clicked.connect(lambda _, rid=rep.id: self._export_csv(rid))

            act_layout.addWidget(btn_approve)
            act_layout.addWidget(btn_xlsx)
            act_layout.addWidget(btn_csv)
            self.table.setCellWidget(r, 6, act_widget)

        self.card_total.set_value(str(len(reports)))
        self.card_drafts.set_value(str(draft_count))
        self.card_approved.set_value(str(approved_count))

    def _on_generate_wizard_clicked(self) -> None:
        if not self.current_engagement:
            QMessageBox.warning(
                self, "No Engagement", "Please select an active audit engagement first."
            )
            return

        dlg = ReportWizardDialog(self.current_engagement.id, self.report_service, parent=self)
        if dlg.exec():
            self.refresh()
            self.report_changed.emit()

    def _approve_report(self, report_id: str) -> None:
        res = QMessageBox.question(
            self,
            "Confirm Report Approval",
            "Approve report and remove 'DRAFT' watermark?\n\n"
            "Notice: Approval is an internal workflow attestation and audit record, NOT an IT Act 2000 PKI DSC.",
            QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No,
        )
        if res == QMessageBox.StandardButton.Yes:
            self.report_service.approve_report(
                ApproveReportDTO(
                    report_id=report_id,
                    approved_by="Audit Partner",
                    approver_role="Partner",
                )
            )
            QMessageBox.information(
                self, "Report Approved", "Report approved! Watermark removed from PDF."
            )
            self.refresh()
            self.report_changed.emit()

    def _export_xlsx(self, report_id: str) -> None:
        path = self.report_service.export_to_xlsx(
            ExportReportDTO(report_id=report_id, export_format=ExportFormatEnum.XLSX)
        )
        QMessageBox.information(
            self, "XLSX Exported", f"Successfully exported formula-escaped XLSX to:\n{path}"
        )

    def _export_csv(self, report_id: str) -> None:
        path = self.report_service.export_to_csv(
            ExportReportDTO(report_id=report_id, export_format=ExportFormatEnum.CSV)
        )
        QMessageBox.information(
            self, "CSV Exported", f"Successfully exported formula-escaped CSV to:\n{path}"
        )
